[package]
name = "fdk-mail-sender-service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.0"
cronjob = "0.4.17"
lazy_static = "1.4.0"
lettre = "0.10.1"
prometheus = "0.13.3"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.94"
thiserror = "1.0.38"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.15", features = ["fmt", "json"] }
