[package]
name = "fdk-mail-sender-service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
cronjob = "0.4.17"
lazy_static = "1.4.0"
lettre = "0.10.4"
prometheus = "0.13.3"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.95"
thiserror = "1.0.40"
tracing = "0.1.39"
tracing-subscriber = { version = "0.3.16", features = ["fmt", "json"] }
