[package]
name = "fdk-mail-sender-service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.1.0"
cronjob = "0.4.17"
lazy_static = "1.4.0"
lettre = "0.10.0-rc.7"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
thiserror = "1.0.31"
tracing = "0.1"
tracing-subscriber = "0.2"
